### ISSUE TITLE
bc_module_battery_get_voltage() always returns 0

### ISSUE THREAD

**Issue by mkyral** [bigclownlabs/bcf-sdk-core-module#138]
Since commit bcb25bd527ae0019bb25fc1fcda386e3335e8bdd the `bc_module_battery_get_voltage()` function always returns 0V.

Works correctly in https://github.com/bigclownlabs/bcf-generic-node/releases/tag/v1.5.0 and does not works in https://github.com/bigclownlabs/bcf-generic-node/releases/tag/v1.5.5

The reason seams to be there: https://github.com/bigclownlabs/bcf-sdk-core-module/blob/master/bcl/src/bc_adc.c#L222

The `BC_ADC_FORMAT_FLOAT` part is commented out. When I uncomment it, the `bc_module_battery_get_voltage()` function works again. Only returns little bit bigger value (6.32V in generic-node v1.5.0 vs. 6.75V in latest).

Is there any reason, why was this part commented out?

**Comment by hubpav** [comment]
Hi, thanks for pointing this out - at the moment we are re-implementing the ADC behavior (it will be all relative) and it should be resolved this week.  For the moment being, please use the implementation from the former commit. Sorry about the confusion!

**Comment by mkyral** [comment]
OK. Will wait ;-)

**Comment by blavka** [comment]
Fixed, I return previous functionality.
